#!/bin/bash

# Update and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo cat <<EOF > /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 STUDENT_ID-web-01:80 check
    server web-02 STUDENT_ID-web-02:80 check
EOF

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Restart HAProxy
sudo systemctl restart haproxy

echo "HAProxy configured and started."

